version: '2'
services:
  reverifi-api:
    container_name: reverifi-api
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - BASE_URL=https://reverifi.sociumtech.com
      - CORS_ORIGIN=*
      - DB_HOST=reverifi-db
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - NODE_ENV=production
      - NOTIFICATION_EMAIL_SENDER=
      - NOTIFICATION_SMS_SENDER=
      - PORT=3000
      - SECRET=AK
      - SMTP_HOST=
      - SMTP_PASSWORD=
      - SMTP_PORT=
      - SMTP_USER=
      - TWILIO_ACCOUNT_SID=AC67c2883d8b74d446597ea7face2c575a
      - TWILIO_AUTH_TOKEN=c8a2242f8b32136082c39b7782f08477
      - VIRTUAL_HOST=reverifi-api.docker
      - GCLOUD_STORAGE_BUCKET=reverifi-default
      - GCLOUD_PROJECT=reverifi-342815
      - GOOGLE_APPLICATION_CREDENTIALS=src/config/gcs.json
      - MAIL_CHIMP_API_KEY=169ffb3074fa80e3dec5736bbe2acde2-us14
      - MAIL_CHIMP_SERVER=us14
      - MAIL_CHIMP_LIST_ID=8a55115bd4

    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/app
    depends_on:
      - reverifi-db
    command: ['bin/boot.sh']

  reverifi-db:
    container_name: reverifi-db
    image: postgres:14.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      VIRTUAL_HOST: reverifi-db.docker
    ports:
      - 5432
