const Router = require('express-promise-router');

const authRouter = require('./auth');
const usersRouter = require('./users');
const docsRouter = require('./api-docs');
const listingsRouter = require('./listings');
const companiesRouter = require('./companies');
const rolesRouter = require('./roles');
const propertyTypesRouter = require('./property-types');
const listingTypesRouter = require('./listing-types');
const featuresRouter = require('./features');
const schedule = require('./schedule');
const socialStatisticsRouter = require('./social-statistics');
const ratingCriteriaRouter = require('./rating-criteria');
const reviewsRouter = require('./reviews');
const invitationsRouter = require('./invitations');
const processesRouter = require('./processes');
const transactionsRouter = require('./transactions');
const uploadRouter = require('./upload');
const actionTypesRouter = require('./action-types');
const userActionTypesRouter = require('./user-action-types');
const offerRouter = require('./offer');
const notificationChannelsRouter = require('./notification-channels');
const notificationsRouter = require('./notifications');

const router = Router();

router.use('/api-docs', docsRouter);
router.use('/api/auth', authRouter);
router.use('/api/users', usersRouter);
router.use('/api/listings', listingsRouter);
router.use('/api/companies', companiesRouter);
router.use('/api/roles', rolesRouter);
router.use('/api/property-types', propertyTypesRouter);
router.use('/api/listing-types', listingTypesRouter);
router.use('/api/features', featuresRouter);
router.use('/api/schedule', schedule);
router.use('/api/social-statistics', socialStatisticsRouter);
router.use('/api/rating-criteria', ratingCriteriaRouter);
router.use('/api/reviews', reviewsRouter);
router.use('/api/invitations', invitationsRouter);
router.use('/api/processes', processesRouter);
router.use('/api/transactions', transactionsRouter);
router.use('/api/upload', uploadRouter);
router.use('/api/action-types', actionTypesRouter);
router.use('/api/user-action-types', userActionTypesRouter);
router.use('/api/offer', offerRouter);
router.use('/api/notification-channels', notificationChannelsRouter);
router.use('/api/notifications', notificationsRouter);

module.exports = router;
