name: Run Test & Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: 'Test & Coverage'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Test & Coverage
        run: npm run test
